- job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node_export
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['100.28.246.10:8080']
  - job_name: node_export_masterk8s
    static_configs:
      - targets: ["34.230.45.232:9100"]
